### ISSUE TITLE
Broken Stochastic Depth Layer

### ISSUE THREAD

**Issue by dc250601** [sayakpaul/swin-transformers-tf#10]
The Stochastic Depth Layer does not seem to work due to mismatch of matmul tensors.
Change to the 'shape' variable in the StochasticDepth layer seems to fix the issue.
shape = (tf.shape(x)[0],) + (1,) * (tf.shape(tf.shape(x)) - 1) ---> shape = (x.shape[0],)+(1,)*(tf.shape(x).shape[0]-1)

**Comment by sayakpaul** [comment]
Feel free to drop a PR.

**Comment by sayakpaul** [comment]
#11
